export const actionConstants = {
    ADD_TO_CART:"ADD_TO_CART",
    ADD_TO_FAVOURITE:"ADD_TO_FAVOURITE",
    REMOVE_FROM_CART:"REMOVE_FROM_CART",
    REMOVE_FROM_FAVOURITE:"REMOVE_FROM_FAVOURITE",
    SET_CART:"SET_CART",
    SET_FAV:"SET_FAV",
}