
export const stringConstants = {
    songs_list: 'Songs Listing',
    search : 'Search...',
    album : 'Album',
    artist: 'Artist',
    duration : 'Duration',
    addToFav: 'Like',
    buy: 'Buy',
    cart: 'Cart',
    favourites:'Favourites',
    followers: 'Followers',
    releaseDate: 'Release Date',
    rating: 'Rating',
    albums: 'Albums',
    fans: 'Fans',
    remove: 'Remove',
    nosongaddedtocart:'No song added to cart',
    searchYourMusicHere:'Search Your Music Here',
    addedToCart:"Added to cart",
    removedFromCart:"Removed from cart",
    notAdded:"Item already added",
    notRemoved:"Not Added",
    addedToFav:"Added to favourites",
    removedFromFav:"Removed from favourites",
    allSongs: "All Songs",
    noMusicFound:"No Music Found",
    myCart:"My Cart",
    myFavourites:'My Favourites',
}